use assert_cmd::cargo::cargo_bin_cmd;
use std::fs;
use tempfile::tempdir;

#[test]
fn extern_bind_generates_wrappers() {
    let dir = tempdir().expect("temp dir");
    let header = dir.path().join("sample.h");
    let output = dir.path().join("bindings.ch");
    fs::write(&header, c_header()).expect("write header");

    cargo_bin_cmd!("chic")
        .args([
            "extern",
            "bind",
            "--library",
            "sample",
            "--header",
            header.to_str().expect("utf8 header"),
            "--namespace",
            "Tests.Interop",
            "--output",
            output.to_str().expect("utf8 output"),
        ])
        .assert()
        .success();

    let contents = fs::read_to_string(&output).expect("read generated file");
    assert!(
        contents.contains("// <auto-generated by chic extern bind>"),
        "expected auto-generated banner"
    );
    assert!(
        contents.contains("namespace Tests.Interop;"),
        "expected namespace declaration"
    );
    assert!(
        contents.contains("public static extern int add_values"),
        "expected function binding"
    );
    assert!(
        contents.contains("*const byte message"),
        "expected pointer parameter mapping"
    );
}

fn c_header() -> &'static str {
    r#"
#pragma once

int add_values(int left, int right);
double scale_value(double value, double factor);
const char* format_message(const char* message);
"#
}
