name: Feature request
description: Propose a new feature for Chic
title: "feature: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Is Chic missing a feature you’d like to see? Propose it here.

        Before you submit a feature request:
        1. Search existing issues for similar requests. If you find one, 👍 it rather than opening a new issue.
        2. Large changes (language or runtime contract) typically need discussion before implementation.

  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
      description: Describe the desired behavior or API at a high level.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: What problem does it solve? Who is it for?
    validations:
      required: false

  - type: textarea
    id: spec_impact
    attributes:
      label: Spec impact (optional)
      description: If this changes the language or runtime contract, link to the relevant spec section and describe the change.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional information
      description: Links, prior art, sketches, or constraints we should know about.
    validations:
      required: false
