use super::*;

pub(super) use crate::frontend::ast::{Item, StatementKind as AstStatementKind};
pub(super) use crate::frontend::diagnostics::Span;
pub(super) use crate::frontend::parser::parse_module;
pub(super) use crate::mir::data::{
    BinOp, BlockId, BorrowKind, CastKind, ConstOperand, ConstValue, InlineAsmOperandKind,
    InlineAsmRegister, InlineAsmTemplatePiece, InterpolatedStringSegment, LocalId, LocalKind,
    MirBody, Operand, ParamMode, PatternProjectionElem, ProjectionElem, Rvalue, StatementKind,
    StrId, Terminator, Ty,
};
pub(super) use crate::mir::layout::TypeLayout;
pub(super) use crate::mir::verify::verify_body;
mod accelerator;
mod alias_contract;
mod array_literals;
mod as_casts;
mod async_promotion;
mod async_support;
mod atomics;
mod basics;
mod borrows;
mod cache;
mod call_modifiers;
mod calls;
mod checked;
pub(super) mod common;
mod constructors;
mod consts;
mod control_expressions;
mod control_flow;
mod conversions;
mod decimal_intrinsics;
mod default_arguments;
mod delegates;
mod di;
mod exceptions;
mod externs;
mod function_pointers;
mod impl_trait;
mod inline_asm;
mod intrinsics;
mod lambdas;
mod mmio;
mod named_arguments;
mod nameof;
mod new_expr;
mod null_coalesce;
mod operators;
mod overloads;
mod patterns;
mod properties;
mod quote;
mod reflect;
mod required;
mod resources;
mod sizeof;
mod span_conversions;
mod state_machine;
mod statements;
mod statics;
mod strings;
mod switches;
mod testcases;
mod traits;
mod types;
mod unsafe_pointers;
mod variance;
mod vectorize;
mod virtual_dispatch;
